# Generated by Django 4.1.2 on 2022-11-12 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0002_alter_orderproduct_order_alter_orderproduct_product_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="backend.category",
                verbose_name="Категория",
            ),
        ),
    ]
