# Generated by Django 4.1.2 on 2022-11-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopproducts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="backend.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="shopproducts",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="backend.shop",
                verbose_name="Магазин",
            ),
        ),
    ]
