# Generated by Django 4.1.2 on 2022-11-13 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_shopproducts_product_alter_shopproducts_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Orders",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrderProducts",
                to="backend.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrderProducts",
                to="backend.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrderProducts",
                to="backend.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="shop_products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrderProducts",
                to="backend.shopproducts",
                verbose_name="Наличие в магазине",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="user",
            field=models.ForeignKey(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="OrderProducts",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="backend.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="user",
            field=models.ForeignKey(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="shops",
            ),
        ),
        migrations.AlterField(
            model_name="shopproducts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ShopProducts",
                to="backend.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="shopproducts",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ShopProducts",
                to="backend.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="shopproducts",
            name="user",
            field=models.ForeignKey(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ShopProducts",
            ),
        ),
    ]
