# Generated by Django 4.1.2 on 2022-11-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_category_user_alter_order_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderproduct", name="order",),
    ]
