# Generated by Django 4.1.2 on 2022-11-13 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_delete_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="user",
            field=models.ForeignKey(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrderProducts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="OrderProducts",
            ),
        ),
    ]
