# Generated by Django 4.1.2 on 2022-11-13 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_alter_orderproduct_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrderProducts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="OrderProducts",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
