# Generated by Django 4.1.2 on 2022-11-14 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_user_is_email_active"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderproduct", name="status",),
        migrations.AddField(
            model_name="orderproduct",
            name="order",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified", models.DateTimeField(auto_created=True, auto_now=True)),
                (
                    "create_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("basket", "Статус корзины"),
                            ("confirmed", "Подтвержден"),
                            ("assembled", "Собран"),
                            ("sent", "Отправлен"),
                            ("delivered", "Доставлен"),
                            ("canceled", "Отменен"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Ordeк",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы",},
        ),
    ]
